ProductList:
  get:
    tags: [💻Products]
    summary: Get all Products
    description: Retrieve the complete list of products with their associated categories and vendors.
    responses:
      "200":
        description: List of products retrieved successfully.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "./components/schemas/Product"
      "500":
        description: Internal server error

ProductFilter:
  get:
    tags: [💻Products]
    summary: Get Products with filters
    description: Retrieve a filtered list of products based on organization, query string, category, and vendor.
    parameters:
      - name: organizationId
        in: query
        required: false
        schema:
          type: integer
        description: Filter by organization ID
      - name: query
        in: query
        required: false
        schema:
          type: string
        description: Search query for product name or product number
      - name: category
        in: query
        required: false
        schema:
          type: integer
        description: Filter by category ID
      - name: vendor
        in: query
        required: false
        schema:
          type: integer
        description: Filter by vendor ID
    responses:
      "200":
        description: Filtered list of products retrieved successfully.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "./components/schemas/Product"
      "400":
        description: Bad request - invalid filter parameters
      "500":
        description: Internal server error

ProductById:
  get:
    tags: [💻Products]
    summary: Get Product details by ID
    description: Retrieve detailed information for a specific product using its unique ID.
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: Unique ID of the product
    responses:
      "200":
        description: Product details retrieved successfully.
        content:
          application/json:
            schema:
              $ref: "./components/schemas/Product"
      "404":
        description: Product not found
      "500":
        description: Internal server error

ProductDelete:
  delete:
    tags: [💻Products]
    summary: Delete a Product
    description: Delete a specific product by its ID and organization ID.
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: Unique ID of the product to delete
      - name: organizationId
        in: path
        required: true
        schema:
          type: integer
        description: Organization ID associated with the product
    responses:
      "200":
        description: Product deleted successfully.
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                productId:
                  type: integer
      "404":
        description: Product not found
      "500":
        description: Internal server error

ProductAdd:
  post:
    tags: [💻Products]
    summary: Add a new Product
    description: Create a new product with the provided details.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "./components/schemas/AddProductRequest"
    responses:
      "201":
        description: Product created successfully.
        content:
          application/json:
            schema:
              $ref: "./components/schemas/Product"
      "400":
        description: Bad request - invalid input data
      "500":
        description: Internal server error

ProductEdit:
  post:
    tags: [💻Products]
    summary: Edit an existing Product
    description: Update an existing product with the provided details.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "./components/schemas/EditProductRequest"
    responses:
      "200":
        description: Product updated successfully.
        content:
          application/json:
            schema:
              $ref: "./components/schemas/Product"
      "400":
        description: Bad request - invalid input data
      "404":
        description: Product not found
      "500":
        description: Internal server error
